// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzninuepdvupetwqxbju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bmludWVwZHZ1cGV0d3F4Ymp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDAzNTIsImV4cCI6MjA3MTQ3NjM1Mn0.QTh-eFV3PqGbDBeqsdwRGJmy4u0bY9gBpIu-JiUuQvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});